[package]
name = "RustKnight"
version = "0.1.3"
edition = "2021"
[dependencies]
chess = "3.2.0"
rand = "0.8"
lazy_static = "1.4"
dashmap = "5.5.3"
[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
